### ISSUE TITLE
Change page displayed after login

### ISSUE THREAD

**Issue by macecchi** [fangli/django-saml2-auth#19]
Hi, 

I'm trying to make my application redirect to `/` instead of `/admin` after the login.
In #5, you mention adding the `next` parameter, but I'm not sure where I should add this.

I'm using this plugin to integrate with Okta.

Cheers,
Mario

**Comment by macecchi** [comment]
To clarify, I'm talking about the page that opens when launching the app from Okta.

**Comment by ayr-ton** [comment]
I'm having the same situation here.

**Comment by fangli** [comment]
Hi,

There are two different scenarios.

If the visitor initiate the access within the django app, you can redirect the user from an unauthorized URL to the pre-defined login page, and set "?next=/the/path/you/want/after/login" in the target URL, such as "/user/login?next=/the/path/you/want/after/login". Yes of course you need set "url(r'^user/login/$', django_saml2_auth.views.signin)" in url.py, as what I mentioned in README.

If the visitor initiate the access from OKTA, there is no way to set the default *next* URL, it will always be /admin.
But since your requirement is quite reasonable and it's nice to have, I'll have it implemented in the next release(maybe in couple hours).

Will keep you updated.

**Comment by fangli** [comment]
Hi @macecchi @ayr-ton could you please update the package to latest version 2.1.0?
pip install django-saml2-auth==2.1

Now it support the default post-login redirect URL by setting DEFAULT_NEXT_URL under settings.SAML2_AUTH, such as "/your/own/url".

Please let me know if it works.

**Comment by macecchi** [comment]
Thanks @fangli! I updated the plugin and setting `DEFAULT_NEXT_URL` to `/` gave me exactly what I wanted! 🎉

**Comment by ayr-ton** [comment]
Thanks for all the help, @fangli o/

**Comment by RazazR** [comment]
> Hi,
> 
> I'm trying to make my application redirect to `/` instead of `/admin` after the login. In #5, you mention adding the `next` parameter, but I'm not sure where I should add this.
> 
> I'm using this plugin to integrate with Okta.
> 
> Cheers, Mario

RazazR_
